# Generated by Django 3.2 on 2022-07-04 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('pkid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('location', models.CharField(max_length=200, verbose_name='Location')),
                ('photo', models.ImageField(default='defautl_profile.png', upload_to='')),
                ('is_married', models.BooleanField(default=False, verbose_name='Marital Status')),
                ('bio', models.TextField(verbose_name='About Yourselef')),
                ('proffession', models.CharField(max_length=255, verbose_name='What you do for a living')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
